/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container-high": "#dee9fd",
        "on-error": "#ffffff",
        "inverse-on-surface": "#ebf1ff",
        "surface-dim": "#d0daef",
        "outline-variant": "#bccabb",
        "inverse-primary": "#4de082",
        "outline": "#6d7b6d",
        "primary-container": "#4ade80",
        "tertiary-container": "#d9c46c",
        "on-tertiary-fixed": "#221b00",
        "on-secondary": "#ffffff",
        "surface": "#f9f9ff",
        "on-secondary-fixed-variant": "#3e4943",
        "secondary": "#55615a",
        "secondary-container": "#d9e6dd",
        "surface-container-low": "#eff3ff",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "primary-fixed": "#6dfe9c",
        "secondary-fixed-dim": "#bdcac1",
        "on-surface": "#121c2a",
        "surface-container": "#e6eeff",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f9ff",
        "on-surface-variant": "#3d4a3e",
        "secondary-fixed": "#d9e6dd",
        "tertiary-fixed-dim": "#dcc66e",
        "background": "#f9f9ff",
        "on-primary-container": "#005e2d",
        "surface-container-highest": "#d9e3f7",
        "tertiary-fixed": "#f9e287",
        "on-background": "#121c2a",
        "surface-tint": "#006d36",
        "on-secondary-container": "#5b6760",
        "primary-fixed-dim": "#4de082",
        "on-error-container": "#93000a",
        "surface-variant": "#d9e3f7",
        "on-secondary-fixed": "#131e19",
        "primary": "#006d36",
        "on-primary-fixed-variant": "#005227",
        "tertiary": "#6e5e0d",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#5f5000",
        "inverse-surface": "#273140",
        "on-primary-fixed": "#00210c",
        "on-tertiary-fixed-variant": "#534600"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "1.5rem",
        "container-padding": "2rem",
        "stack-sm": "0.5rem",
        "base": "8px",
        "stack-lg": "3rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "800"}],
        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-lg": ["14px", {"lineHeight": "20px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
