export const menuItems = [
    {
        id: 1,
        name: 'Classic Burger',
        category: 'Fast Food',
        price: '55,000đ',
        rawPrice: 55000,
        rating: 4.8,
        img: 'https://png.pngtree.com/png-vector/20230321/ourmid/pngtree-beef-burger-food-png-image_6655517.png',
        tag: 'Best Seller',
    },
    {
        id: 2,
        name: 'Crispy Chicken',
        category: 'Fast Food',
        price: '45,000đ',
        rawPrice: 45000,
        rating: 4.6,
        img: 'https://png.pngtree.com/png-clipart/20220924/ourmid/pngtree-crispy-fried-chicken-food-png-image_6222027.png',
        tag: 'Hot',
    },
    {
        id: 3,
        name: 'Burger Combo',
        category: 'Food Combo',
        price: '99,000đ',
        rawPrice: 99000,
        rating: 4.9,
        img: 'https://png.pngtree.com/png-clipart/20221001/ourmid/pngtree-fast-food-big-ham-burger-png-image_6244235.png',
        tag: 'Best Seller',
    },
    {
        id: 4,
        name: 'Family Combo',
        category: 'Food Combo',
        price: '179,000đ',
        rawPrice: 179000,
        rating: 4.7,
        img: 'https://png.pngtree.com/png-clipart/20221006/ourmid/pngtree-food-combo-fast-food-png-image_6270777.png',
        tag: '',
    },
    {
        id: 5,
        name: 'Black Forest Cake',
        category: 'Cake',
        price: '65,000đ',
        rawPrice: 65000,
        rating: 4.9,
        img: 'https://png.pngtree.com/png-clipart/20240406/ourmid/pngtree-detailed-black-forest-cake-png-image_12235948.png',
        tag: 'New',
    },
    {
        id: 6,
        name: 'Strawberry Cake',
        category: 'Cake',
        price: '70,000đ',
        rawPrice: 70000,
        rating: 4.8,
        img: 'https://png.pngtree.com/png-vector/20221103/ourmid/pngtree-birthday-strawberry-birthday-cake-png-image_6404248.png',
        tag: '',
    },
    {
        id: 7,
        name: 'Beef Jerky',
        category: 'Dry Food',
        price: '35,000đ',
        rawPrice: 35000,
        rating: 4.5,
        img: 'https://png.pngtree.com/png-clipart/20230922/ourmid/pngtree-premium-fresh-beef-jerky-with-spices-snack-png-image_10143891.png',
        tag: '',
    },
    {
        id: 8,
        name: 'Mixed Nuts',
        category: 'Dry Food',
        price: '49,000đ',
        rawPrice: 49000,
        rating: 4.6,
        img: 'https://png.pngtree.com/png-vector/20231030/ourmid/pngtree-mixed-nuts-png-image_10291097.png',
        tag: 'New',
    },
];

export const categories = ['All', 'Fast Food', 'Food Combo', 'Cake', 'Dry Food'];
